### ISSUE TITLE
Tablas duplicadas: unidades y unidads

### ISSUE THREAD

**Issue by FlyingPumba** [FlyingPumba/mte-uba#16]
Estaba leyendo el schema y vi que tenemos esas dos tablas.
Algún interesado en arreglar esto ? jaj
No sé cual de las dos es la posta.

**Comment by FlyingPumba** [comment]
cc: @mnofresno @matiasamd

**Comment by mnofresno** [comment]
@FlyingPumba fijate por que no deberías tener dos tablas. Con los últimos cambios solo deberías tener "unidades". Si ves que te está quedando una tabla más, yo haría rake db:drop, rake db:create y rake db:migrate para empezar la migración desde cero con una base limpia. No debería haber problema!

**Comment by FlyingPumba** [comment]
@mnofresno tenías razón, gracias !
