### ISSUE TITLE
Unificar modelos de NotaReparacion y Nota Pedido en modelo Comprobante

### ISSUE THREAD

**Issue by matiasamd** [FlyingPumba/mte-uba#17]

**Comment by FlyingPumba** [comment]
@matiasamd como viene esto ?

**Comment by FlyingPumba** [comment]
Veo el modelo "comprobante" en la carpeta models, pero no veo que nota pedido y nota reparacion se relacionen con comprobante.

**Comment by FlyingPumba** [comment]
Okey, comprobé que todavía está a medias (la ruta de new de nota de pedido, por ejemplo , crashea porque le falta unos params).
@matiasamd esto te lo voy a tener que dejar a vos, traté de entender lo de los comprobables y no pude.

**Comment by FlyingPumba** [comment]
Al final quedaron separados en dos.
Por ahora quizás no tenga mucha utilidad, pero más adelante quizás tengan reglas distintas los modelos.

**Comment by FlyingPumba** [comment]
De hecho, la nota de reparación va a llevar en algún momento un campo "remito"
