### ISSUE TITLE
Generar y autocompletar los números de serie de nota de pedido y reparacion automaticamente

### ISSUE THREAD

**Issue by FlyingPumba** [FlyingPumba/mte-uba#26]
Se puede directamente usar el id de los objetos.

**Comment by matiasamd** [comment]
Tal vez se puede cambiar el numeroserie para dividirlo como en dos partes, una parte que sea un modelo nuevo, tipo "serie" o "talonario" que sea alfanumerico y despues un numero que si sea numerico, entonces es mucho más simple que se autonumeren, no se si se entendio lo que puse jajaja

**Comment by FlyingPumba** [comment]
Por mi me da lo mismo, pero la parte alfanumerica como un "talonario" ni idea como se hace. Quizás trae más confusión, hay que ver si realmente aporta.

**Comment by FlyingPumba** [comment]
Por ahora lo puse con el id, quizás más adelante lo cambiamos.
