### ISSUE TITLE
Cargar una nueva unidad

### ISSUE THREAD

**Issue by FlyingPumba** [FlyingPumba/mte-uba#3]
Una unidad consiste en:
- patente: string
- marca: string
- año: integer
- fuera de servicio: boolean

Además,
Tiene un chofer asignado al turno mañana y un chofer para el turno noche.

**Comment by mnofresno** [comment]
Propongo que agreguemos al modelo de dominio una entidad Turno que se relacione con una tabla intermedia con la unidad y el chofer. De este modo si en el futuro se agregan más turnos solo hay que agregar un registro a la tabla correspondiente.

**Comment by FlyingPumba** [comment]
@mnofresno creo que no hace falta eso. Si el día de mañana aparece turno "tarde", creo que alcanza con agregar al modelo: `has_one :choferTarde, class_name:'Chofer'`

**Comment by FlyingPumba** [comment]
Bueno, no puedo lograr que se le asigne dos choferes distintos a la unidad.
Pero creo que es lo último que faltaría en cuanto a creación.

**Comment by FlyingPumba** [comment]
Esto ya está andando. Si falta algo se agrega más adelante.
