### ISSUE TITLE
Cargar nuevo chofer

### ISSUE THREAD

**Issue by FlyingPumba** [FlyingPumba/mte-uba#4]
Un chofer consiste en:
- nombre: string
- apellido: string
- radio: string

**Comment by mnofresno** [comment]
Emprolijo el ABM de Choferes agrego combo box para la selección del taller. Más adelante quizás el taller sea el asociado al usuario unicamente. Hago un join en el listado para poder mostrar el nombre del taller.

**Comment by matiasamd** [comment]
No es necesario hacer un join en controlador para poder mostrar el nombre del taller

**Comment by mnofresno** [comment]
Esto lo hablamos con @matiasamd hoy a la tarde, concluímos que quizás hay algún problema en cómo están definidos los modelos Chofer o Taller dado que cuando utilicé Chofer.all sin join en el index del controller, e intenté levantar chofer.taller.nombre desde la vista me arrojó un error diciendo que faltaba un join.

Por otra parte en la documentación de Rails (http://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations) y aquí (http://stackoverflow.com/questions/22985355/ruby-on-rails-how-to-show-foreign-key-values-in-one-model-to-another) recomienda utilizar JOINs o INCLUDES para evitar N+1 queries sql para los listados al momento de utilizar eager loading de una foreign key. De este modo (como se hizo) se genera un JOIN sql al final y es mucho más eficiente que traer el objeto completo por automagia rails.

**Comment by matiasamd** [comment]
Se modifica ABM para que respete la gema formtastic ( Para generar formularios de manera más simple), se quita la selección de chofer, ya que la relación se genera automáticamente en el controlador.
Se agregan breadcrumbs.
Se agregan los turnos de cada chofer en el show.
Se agrega funcionalidad de gema ransack para poder filtrar el index por distintos campos.
